spring.application.name=crud-course
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_course_db
spring.datasource.username=app_user
spring.datasource.password=change_me_postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true